DROP TABLE IF EXISTS food_delivery_orders;

CREATE TABLE food_delivery_orders (
    order_id VARCHAR(20) PRIMARY KEY,
    customer_id VARCHAR(20),
    restaurant_id VARCHAR(20),
    city VARCHAR(50),
    zone VARCHAR(50),
    cuisine_type VARCHAR(50),
    order_datetime TIMESTAMP,
    delivery_partner_id VARCHAR(20),
    delivery_time_minutes INTEGER,
    promised_delivery_time_minutes INTEGER,
    delivery_delay_flag INTEGER,
    order_value NUMERIC(10,2),
    delivery_fee NUMERIC(10,2),
    discount_amount NUMERIC(10,2),
    packaging_charge NUMERIC(10,2),
    platform_commission NUMERIC(10,2),
    refund_amount NUMERIC(10,2),
    rating NUMERIC(3,1),
    payment_method VARCHAR(30),
    customer_tenure_group VARCHAR(30),
    repeat_customer_flag INTEGER,
    acquisition_channel VARCHAR(50),
    order_status VARCHAR(30),
    distance_km NUMERIC(6,2),
    weather_condition VARCHAR(30),
    weekend_flag INTEGER,
    festival_flag INTEGER,
    gross_profit NUMERIC(10,2),
    profit_margin_pct NUMERIC(6,2),
    delay_minutes INTEGER,
    discount_band VARCHAR(30),
    order_month VARCHAR(7)
);
